services:
  frontend:
    container_name: credikfam_front
    image: credikfam-front-app:1.0.0
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    container_name: credikfam_back
    image: credikfam-back-app:1.0.0
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://postgres_db:5432/credikfam
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credikfam 